<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>2. TS - CR to SMS Approve</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>120</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>9ed7fd1c-ead8-4598-b5f4-c91cfb11e210</testSuiteGuid>
   <testCaseLink>
      <guid>ba1fd3ab-7902-4a54-9383-e67fad97dce3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/App - Go Live/FLEET/2. Credit Review/Credit Review - Driven</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>bdd73eb8-b1e5-4e0f-bce7-39b35aed104e</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Application/Fleet/CR to Go Live</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>bdd73eb8-b1e5-4e0f-bce7-39b35aed104e</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>usernameCR</value>
         <variableId>ea945985-13c9-4c1a-aefa-18b93bb8a036</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>bdd73eb8-b1e5-4e0f-bce7-39b35aed104e</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>d2649afb-2dca-4fe5-87ab-d81d0172257a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>bdd73eb8-b1e5-4e0f-bce7-39b35aed104e</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>appNo</value>
         <variableId>2c3337d5-6ed9-45b2-952a-be6adc31013b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>bdd73eb8-b1e5-4e0f-bce7-39b35aed104e</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>notes</value>
         <variableId>b82db83e-4ded-4b89-85d0-0b41e825cd09</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>bdd73eb8-b1e5-4e0f-bce7-39b35aed104e</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>review</value>
         <variableId>96ee849f-b8d9-4b1e-bea6-8ba48813cfb3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>77ba43b4-111f-404f-a6f7-dec7e20e9a75</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9a1e52a1-ff0b-48ec-8a39-1020b656df2f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/App - Go Live/FLEET/SMS Approve/SMS Approve - Driven</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>be31fffc-5207-4875-ac59-d8660d330da6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c2304b28-38d6-402d-8057-05e4081fb5ca</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5137e097-4bf3-4216-86f4-3772734d1217</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>920a6804-6edf-4519-8962-5202ed6ba8f1</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
